### ISSUE TITLE
Something is broken in TZ...

### ISSUE THREAD

**Issue by simonmicro** [Py-KMS-Organization/py-kms#10]
:) I'm already on the next point, no tz defined in python possibly... still investigating. thanks to the nice logs, it should be easy to pinpoint.

_Originally posted by @edgd1er in https://github.com/Py-KMS-Organization/py-kms/issues/3#issuecomment-942653761_

**Comment by simonmicro** [comment]
something like this might be required to define TZ in the entrypoint, still working on it....

#Change timzeone if set
[[ -n ${TZ} ]] && [[ -f /usr/share/zoneinfo/${TZ} ]] && [[ -w /etc/localtime ]] && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime
#use UTC if not
[[ ! -f /etc/localtime ]] && ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime


-> https://github.com/Py-KMS-Organization/py-kms/issues/3#issuecomment-942672079

**Comment by Matthew-Beckett** [comment]
I will need to add this as a fix to the Helm chart

**Comment by edgd1er** [comment]
I have TZ ok (through env var)+ log for client on stdout. 
I try to change now uid/gid of user as I need to have specific id/gid on mounted volume and drop root privileges after having set TZ and UID/GID.. without any luck til now. I might have to split entrypoint in 2. My fork might be already to different from yours.
