### ISSUE TITLE
Cant open WebGUI

### ISSUE THREAD

**Issue by click23** [Py-KMS-Organization/py-kms#100]
I have installed this beloved pykms on a debian distribution linux and tested a bunch of other distros as well, but the only way that I can open WebGUI on port 8080 is docker-compose but I prefer using systemd. I think the documention is not updated or something!
Can you walk me through? I used just the same python3 commands you mentioned and event tried the py-kms-web-gui.kms on port 8080 but all I got was error 84.
Help please!

**Comment by simonmicro** [comment]
Heyho - I have to admit that I did not build the web-ui to work without its specific Docker environment. Could you please send me the specific crash log, so I can further debug this issue?

**Comment by click23** [comment]
unfortunately I have tried to run webui.py file as a systemd but I can't run it so if you have a specific way to run the webui so I can get you the logs, feel free to instruct me.
appreciate your work BTW.

**Comment by didotb** [comment]
@click23 I believe the `pykms_WebUI.py` is based on flask, and it doesn't have the `run()` function called within it. I'm not sure either how it would be normally called since I haven't looked at the entire repo.

If you want to run it manually, you'd have to do a manual `run(host="0.0.0.0", port=8080)` or something similar if you're planning on using flask.

**Comment by didotb** [comment]
after reading a few files I found out [`start.py`](https://github.com/Py-KMS-Organization/py-kms/blob/599574bb607dfc7a9293987dd67d3a7550b28c1c/docker/start.py#L61) inside [`docker`](https://github.com/Py-KMS-Organization/py-kms/tree/master/docker) folder runs the web ui using `gunicorn`. it's in line 61 if you wanna read how it's being run

**Comment by simonmicro** [comment]
> after reading a few files I found out [`start.py`](https://github.com/Py-KMS-Organization/py-kms/blob/599574bb607dfc7a9293987dd67d3a7550b28c1c/docker/start.py#L61) inside [`docker`](https://github.com/Py-KMS-Organization/py-kms/tree/master/docker) folder runs the web ui using `gunicorn`. it's in line 61 if you wanna read how it's being run

Yes, that is it! Thanks for pointing that out. As the UI is indeed written in Flask it must be run using an external WSGI-compatible (or was ist ASGI?) application. In this case I'm using `gunicorn`, but something like `flask run` (https://www.digitalocean.com/community/tutorials/how-to-make-a-web-application-using-flask-in-python-3) should also work, although not recommended for production use...

**Comment by simonmicro** [comment]
Long time, no update - as it works for me, I'll close it.

**Comment by elderlabs** [comment]
It would be advisable to add documentation regarding this. I've created a modified `start.py` file to achieve this, but without proper documentation explaining how to run the web UI outside of Docker, many other users will be left in a similar situation.

**Comment by CRCinAU** [comment]
As a side note, when running in dual stack, the kms component will start with `::` - but the web UI will only start with `0.0.0.0` - meaning no IPv6 on that UI.

**Comment by simonmicro** [comment]
> As a side note, when running in dual stack, the kms component will start with `::` - but the web UI will only start with `0.0.0.0` - meaning no IPv6 on that UI.

Oi... Maybe open a bug-report for that.
