### ISSUE TITLE
Error 0xC004F074 despite successful connection to server

### ISSUE THREAD

**Issue by dstagger** [Py-KMS-Organization/py-kms#105]
Py-KMS doesn't seem to work anymore. I'm trying with Windows 10 LTSC 2019/2021, product key: M7XTQ-FN8P6-TTKYV-9D4CC-J462D and getting error:

Error: 0xC004F074 The Software Licensing Service reported that the computer could not be activated. The Key Management Service (KMS) is unavailable.

**Comment by didotb** [comment]
Have you tried pinging your KMS host device? What device are you using to run Py-KMS? is it in windows running a docker container? perhaps a vm linux machine? or a linux baremetal? we need more info than the error code.

- Your host could have had the IP lease expired and was given a different IP by your DHCP host, this happened to me one time when our ISP decided to update our router's firmware and the DHCP reservation list was reset, gave me a massive headache.
- Some other app could be using port `1688` on the machine Py-KMS is running on.
- If your KMS host is in a VM, make sure it's not behind a NAT. If it's too much work to link the VM network to your physical network, you could run a VPN via ZeroTier or Wireguard and use the VPN IP of your KMS host instead.

**Comment by demostenescz666** [comment]
I have same issue, running py-kms on other windows server (no docker), trying to activate server 2022 . Py-kms is contacted, this is in log for each activation attempt:  WARNING  Module 'tzlocal' or 'pytz' not available ! Request time not localized.

**Comment by didotb** [comment]
It seems like Py-KMS is receiving the requests but the clients aren't receiving the replies
Performing a network sniff with wireshark might show the underlying problem.

**Comment by demostenescz666** [comment]
Network is perfectly OK. Both computers have opened 1688 port for outgoing/incomming, they are on same vlan and traffic between them works.

**Comment by didotb** [comment]
> Network is perfectly OK. Both computers have opened 1688 port for outgoing/incomming, they are on same vlan and traffic between them works. Is there some debug mode to see what exactly was send as reply?

you can enable debug logs, should be a text file located at where you specified it to be

**Comment by didotb** [comment]
@dstagger @demostenescz666 I just remembered that you can also view KMS activation errors via `Event Viewer`
It should be in `Windows Logs` then `System`. Perform `skms.vbs /ato`, then refresh the logs after the error, read through every warning and error for the current time, and it should give you a more detailed reason why ***hopefully***

**Comment by simonmicro** [comment]
I'll go ahead and close this one (feel free to reopen), as I feel this is just another connection problem by the user.

**Comment by demostenescz666** [comment]
I dont think it is connection issue, as I wrote, server received it, but it sending nothing back. I installed original windows activation service and it works. But close it if you want, I dont have time to debug this.

**Comment by extratype** [comment]
I have the same issue, I was using Python 3.12 so I downgraded python and it worked.

**Comment by biom4st3r** [comment]
Same. Python 3.10.14 works for me, but not 3.12

**Comment by dstagger** [comment]
I'm hosting py-kms on docker in diet pi. No network issues. Please reopen this issue
