### ISSUE TITLE
Docker not working

### ISSUE THREAD

**Issue by virgo77** [Py-KMS-Organization/py-kms#107]
Hi there!
I'm trying to deploy the Docker PY-KMS solution, but the container is stuck on "starting".

I'm on Ubuntu Server 22.04 with latest docker and portainer
Some of my containers works fine. But not py-kms
![image](https://github.com/Py-KMS-Organization/py-kms/assets/23108339/17e9e03f-aeb6-4f9d-bc4f-cb35ba17daf0)

I tried:
```
docker pull ghcr.io/py-kms-organization/py-kms
docker run -d --name KMSServer --restart always -p 1688:1688 ghcr.io/py-kms-organization/py-kms
or
docker run -d --name KMSServer --restart always -p 0.0.0.0:1688:1688 ghcr.io/py-kms-organization/py-kms
or
docker run -d --name KMSServer --restart always -p 192.168.1.230:1688:1688 ghcr.io/py-kms-organization/py-kms
```

Same with these 2 ones:
```
docker pull ghcr.io/py-kms-organization/py-kms:latest
docker pull ghcr.io/py-kms-organization/py-kms:python3
```
I took a look at your 'wiki' https://py-kms.readthedocs.io/en/latest/
maybe I'm doing something wrong?

Note that if I install it like a service, it runs well.
But I would prefer to launch it on docker, as Ubuntu Server is just used for this purpose. Nothing else :)

Any ideas?
Thanks a lot

**Comment by virgo77** [comment]
Damn... I don't undestand... It's for 2 hours I'm trying... and look!
![image](https://github.com/Py-KMS-Organization/py-kms/assets/23108339/1a41a28a-6b0d-4a9e-a665-15f093ade75b)

I tried an activation and it worked...
Don't know what happened.

I'm really sorry to bother you... really!
you can close this topic.

Sorry again

V.

**Comment by didotb** [comment]
You should enable logs if possible, in-case this happens again in the future.
You could also try opening the container's console output, might show something there as well.

**Comment by RocketImps** [comment]
> Just a question: is it good to see "healthy" or should I have to see "running"?
> 
> I'm really sorry to bother you...
> 
> V.

On first run the container can take a several minutes to stabilize. Healthy means the docker container is functioning properly. 

Your screenshots imply the container started up & is healthy which allowed activation.  Portainer will use the color red for errors, orange for warnings & grey to indicate a container is not active. Green is good
