### ISSUE TITLE
IPv4 [0.0.0.0] can't be dualstack

### ISSUE THREAD

**Issue by dontcrash** [Py-KMS-Organization/py-kms#108]
Had some issues on an Ubuntu VM with Netplan and IPv6 forcing it to wait for network on boot every single time, so I disabled it in grub.
py-kms now refuses to run and spits out an error, even when I manually specify 0.0.0.0 as the IP to bind to.

I believe the issue lies in the pykms_Server.py srv_options array:

https://github.com/Py-KMS-Organization/py-kms/blob/35fbc766caf76697ae29d130d663825318e40fac/py-kms/pykms_Server.py#L214
https://github.com/Py-KMS-Organization/py-kms/blob/35fbc766caf76697ae29d130d663825318e40fac/py-kms/pykms_Server.py#L215

This line should be False by default (if the description is to be believed).

**Comment by didotb** [comment]
If you've changed it on your repo and works, you could submit a PR to update this repo.

#

> Had some issues on an Ubuntu VM with Netplan and IPv6 forcing it to wait for network on boot every single time, so I disabled it in grub.

I got curious though, was the wait description on boot something along "Wait for network to be configured"? I had the same problem last week, I just [followed this](https://askubuntu.com/questions/1421785/a-start-job-is-running-for-wait-for-network-to-be-configured-because-ipv6-blocke) and I didn't have to disable anything in grub.

**Comment by dontcrash** [comment]
> If you've changed it on your repo and works, you could submit a PR to update this repo.
> 
> > Had some issues on an Ubuntu VM with Netplan and IPv6 forcing it to wait for network on boot every single time, so I disabled it in grub.
> 
> I got curious though, was the wait description on boot something along "Wait for network to be configured"? I had the same problem last week, I just [followed this](https://askubuntu.com/questions/1421785/a-start-job-is-running-for-wait-for-network-to-be-configured-because-ipv6-blocke) and I didn't have to disable anything in grub.

Yes it was, I may have a look at iptables, could be something funky there.
Will submit a PR to this repo.

**Comment by simonmicro** [comment]
While this was indeed a mistake in the help text, please read the `README`, which states:

> **In case your OS does not support IPv6, make sure to explicitly specify the legacy IPv4 of `0.0.0.0`!**

I did not notice the horrible implications of the proposed changes until now... :fire:

**Comment by dontcrash** [comment]
> While this was indeed a mistake in the help text, please read the `README`, which states:
> 
> > **In case your OS does not support IPv6, make sure to explicitly specify the legacy IPv4 of `0.0.0.0`!**
> 
> I did not notice the horrible implications of the proposed changes until now... 🔥

I did manually specify the bind to 0.0.0.0, still got the same error message until I flipped the default bool mentioned here
