### ISSUE TITLE
Recent Change to IPv4 and IPv6 Prevents Activation

### ISSUE THREAD

**Issue by miljw002** [Py-KMS-Organization/py-kms#111]
Hi,

I might not be 100% correct, but I think we've got a new issue.

I'm running pyKMS as a docker container on UnRAID - overall works really well. I'm using the ghcr.io/py-kms-organization/py-kms:python3 image.

After upgrading to the version released today the activations have stopped working. If I manually override the pykms_Server.py file it works again.

The only change I can see is line 215 which relates to IPv4 and IPv6 binding being on/off by default. My UnRAID server does have both IPv4 and IPv6 bound to it, and all the internal computers are both IPv4 and IPv6.

I'm not sure if the issue is with UnRAID or the way I've got the network bridging setup (I don't want to consume an entire IP just for this), but it looks like changing this to FALSE breaks things somehow. Changing back to TRUE (by overloading the file), makes things work again.

        'dual'       : {'help' : 'Allows listening to an IPv6 address also accepting connections via IPv4. Deactivated by default.',
                        'def' : True, 'des': "dual"}
        }

I can't see (unless I'm not looking right) a docker ENV variable to change this value. Am I missing something (I'm going to keep looking).

I'm assuming this must be an edge case as I can see this was released and updated on other branches about a week ago, and if this was broken for everyone then someone else would have reported this.

**Comment by didotb** [comment]
It doesn't seem like it's being used in docker, but for those that chose cron instead.
I tried it myself and it feels weird that whenever a user enables `--dual`, it deactivates it instead. I suggest reverting #109 and do it the other way around. As to this issue, I'm not sure if the [line number 262 of pykms_Server.py](https://github.com/Py-KMS-Organization/py-kms/blob/e5f93ff722cffea87e6d44c80b024988cee4c01f/py-kms/pykms_Server.py#L262) have something to do with it.

It was forgotten and the `action` argument wasn't changed. Something still feels off though, I'm not quite sure, and I don't think I'll be able to properly understand it while having less than 10 hours of sleep for the entire week already. So I'm hoping this comment would help you guys out.

**Comment by simonmicro** [comment]
Hi. IIRC this flag only changes what type of socket is created... You've mentioned you are using `py-kms` on Unraid, so likely Docker. Which environment variables are you passing the container? Specifically, what are you providing to `IP`? Can it be solved by overwriting the command line and appending `--dual`?
