### ISSUE TITLE
please update to support windows server 2025

### ISSUE THREAD

**Issue by heroes1412** [Py-KMS-Organization/py-kms#122]
please update to support windows server 2025

**Comment by didotb** [comment]
as simonmicro has stated in [their comment here](https://github.com/Py-KMS-Organization/py-kms/issues/87#issuecomment-1527436733), it would be helpful if you could give us some more details so they can add support to it.

some info needed to do that are as follows:
> 
    - SkuId of the CSVLK
    - GroupId
    - MinKeyId
    - MaxKeyId
    - InvalidWinBuild (optional)
>

Alternatively, you can do it your own, and create a PR instead, as I believe simonmicro's busy updating the entire repo fixing some stuff.

**Comment by heroes1412** [comment]
do i need "EPid" ?

**Comment by heroes1412** [comment]
how i can get id value?

			<KmsItem DisplayName="Windows Server 2022" Id="ef6cfc9f-8c5d-44ac-9aad-de6a2ea0ae03" DefaultKmsProtocol="6.0" NCountPolicy="5">
				<SkuItem DisplayName="Windows Server 2022 Datacenter" Id="**ef6cfc9f-8c5d-44ac-9aad-de6a2ea0ae03**" Gvlk="WX4NM-KYWYW-QJJR4-XV3QB-6VM33" />
				<SkuItem DisplayName="Windows Server 2022 Standard" Id="**de32eafd-aaee-4662-9444-c1befb41bde2**" Gvlk="VDYBN-27WPP-V4HQT-9VMD4-VMK7H" />
			</KmsItem>

**Comment by didotb** [comment]
> how i can get id value?

I believe it's the `Activation ID` if you do `slmgr.vbs /dlv`

**Comment by laitco** [comment]
Maybe you find the details in this fork:
https://github.com/heroes1412/py-kms/blob/master/py-kms/KmsDataBase.xml

**Comment by heroes1412** [comment]
This is mine :))

**Comment by laitco** [comment]
> This is mine :))

Maybe @didotb can implement it here.
