### ISSUE TITLE
Multiple conflicting time zone configurations found

### ISSUE THREAD

**Issue by xXcodgerXx** [Py-KMS-Organization/py-kms#124]
I have pykms_Server.py starting from a (user level) crontab with this added line

`@reboot python3 py-kms/pykms_Server.py`

Works well and activates everything. 

But I'm not sure how to resolve this error that shows up in the pykms_logserver.log

Fri, 27 Sep 2024 09:55:09 WARNING  Okay, something went horribly wrong while localizing the request time (proceeding anyways): 'Multiple conflicting time zone configurations found:\n/etc/timezone: Etc/UTC\n/etc/localtime is a symlink to: America/New_York\nFix the configuration, or set the time zone in a TZ environment variable.\n'

[pykms_logserver.log](https://github.com/user-attachments/files/17171855/pykms_logserver.log)

I use 

`timedatectl set-timezone America/New_York`

Which creates the symbolic link

I have pip, tzlocal, and tz installed and set the same time zone there like this 

1)
`tzselect`   (then select the proper options 2)Americas, 49)United States 1) Eastern (most areas) ) - This set the time zone to 'America/New_York'

2)
`sudo tzselect`  ((then select the proper options 2)Americas, 49)United States 1) Eastern (most areas) ) - This set the time zone to 'America/New_York'

3)

`TZ='America/New_York'; export TZ`

Any ideas?

Thank you

**Comment by didotb** [comment]
~~have you tried `dpkg-reconfigure tzdata`? You seem to be running a debian based distro so I based this from [this question on unix stackexchange](https://unix.stackexchange.com/questions/451709/timedatectl-set-timezone-doesnt-update-etc-timezone)~~

Double check `/etc/localtime` where it is a symlink of, you might be able to just delete `/etc/utc`.
Then check contents for `/etc/timezone`, it should only have `America/New_York`

**Comment by xXcodgerXx** [comment]
Yes. It looks like `/etc/timezone` contained `Etc/UTC`  

running

`reconfigure tzdata` changed `/etc/timezone` to `America/New_York`

This was probably the problem - Thanks

**Comment by xXcodgerXx** [comment]
> ~have you tried `dpkg-reconfigure tzdata`? You seem to be running a debian based distro so I based this from [this question on unix stackexchange](https://unix.stackexchange.com/questions/451709/timedatectl-set-timezone-doesnt-update-etc-timezone)~
> 
> Double check `/etc/localtime` where it is a symlink of, you might be able to just delete `/etc/utc`. Then check contents for `/etc/timezone`, it should only have `America/New_York`

That definitely was the problem. Thanks. I guess mark as closed?
