### ISSUE TITLE
Py-KMS with Cloudflare Tunnel ?

### ISSUE THREAD

**Issue by ProTechEx** [Py-KMS-Organization/py-kms#125]
Hey there,

I just deploy py-kms:python3-next container on my Raspberry-PI 4 on my Homelab with:

`docker run -d --name py-kms:python3-next --restart always -p 1688:1688 -p 8080:8080 -v /etc/localtime:/etc/localtime:ro ghcr.io/py-kms-organization/py-kms:python3-next`

The Pi has the static local ip 10.10.10.4

I just add a Cloudflare Tunnel to get accesss from outside throught my subdomain like: kms.mydomain.com
I add as the local Service the Pi IP and the PY-KMS Port, like:  http://10.10.10.4:1688 and as well with tcp://10.10.10.4:1688 to get proxied kms.mydomain.com > 10.10.10.4:1688

![image](https://github.com/user-attachments/assets/97d2b97f-c4be-424e-b15e-1198dbcbb939)

The Office activations does work fine with local IP, but unfortunatelly it doesn't work throught the kms.mydomain.com.

Any ideas ?

**Comment by didotb** [comment]
Security implications from making it available publicly aside; ~~although KMS Activation uses TCP to activate clients, I don't think it can decode HTTP protocol so when it reaches the server, the server simply sees garbage data.~~ Nevermind that crossed out part, I didn't read through your question thoroughly. 

Your clients might still be trying to connect via port `1688` on host `kms.yourdomain.com` but cloudflare gave you a different TCP port so py-kms couldn't see the request.

**Comment by simonmicro** [comment]
If you are using Cloudflare, it will sit in-between the HTTP-server and the client. Cloudflare only supports HTTP and WebSockets. The KMS protocol over `1688` will not work.

To verify just `dig your-domain-over-cloudflare` and see which ip-address is reported.

**Comment by ProTechEx** [comment]
> Cloudflare only supports HTTP and WebSockets.

That’s not true, CF Tunnel also support tcp protocol as well.

**Comment by didotb** [comment]
> That’s not true, CF Tunnel also support tcp protocol as well.

You're right, but the problem then is your clients have to install `cloudflared` in order to connect to the TCP tunneled through cloudflare. It's not readily accessible.

It's kind of the same with hosting your own VPN solution and letting your clients in that VPN service.
This way, it's actually more secure than using cloudflare to expose it to the public.

If you still want to explore that option, there exists youtube videos explaining how the TCP Tunnel works via cloudflare.
