### ISSUE TITLE
Office 2024

### ISSUE THREAD

**Issue by kimchheng-dev** [Py-KMS-Organization/py-kms#126]
Please help to make it work with Office 2024

**Comment by simonmicro** [comment]
I do not use Office. What is the error message. What is the GLVK you used. Any details?!

**Comment by ichadhr** [comment]
with Office 2024. it works!

```
C:\Program Files\Microsoft Office\Office16>cscript //nologo ospp.vbs /act
---Processing--------------------------
---------------------------------------
Installed product key detected - attempting to activate the following product:
SKU ID: 8d368fc1-9470-4be2-8d66-90e836cbb051
LICENSE NAME: Office 24, Office24ProPlus2024VL_KMS_Client_AE edition
LICENSE DESCRIPTION: Office 24, VOLUME_KMSCLIENT channel
Last 5 characters of installed product key: GCVGB
<Product activation successful>
---------------------------------------
Installed product key detected - attempting to activate the following product:
SKU ID: 923fa470-aa71-4b8b-b35c-36b79bf9f44b
LICENSE NAME: Office 24, Office24VisioStd2024VL_KMS_Client_AE edition
LICENSE DESCRIPTION: Office 24, VOLUME_KMSCLIENT channel
Last 5 characters of installed product key: WQQTV
<Product activation successful>
---------------------------------------
Installed product key detected - attempting to activate the following product:
SKU ID: aaea0dc8-78e1-4343-9f25-b69b83dd1bce
LICENSE NAME: Office 24, Office24ProjectPro2024PreviewVL_KMS_Client_AE edition
LICENSE DESCRIPTION: Office 24, VOLUME_KMSCLIENT channel
Last 5 characters of installed product key: JB89R
<Product activation successful>
---------------------------------------
---------------------------------------
---Exiting-----------------------------
```

**Comment by kimchheng-dev** [comment]
1. I download from this source https://officecdn.microsoft.com/db/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-us/ProPlus2024Retail.img.
==> After installation I got this "Last 5 characters of installed product key: R9GQV" which is different from yours.

2. Then try to manual apply key: XJ2XN-FW8RK-P4HMP-DKDBV-GCVGB
==> Then I got the following issue:
C:\Windows\system32>cscript //nologo "C:\Program Files\Microsoft Office\Office16\ospp.vbs" /inpkey:XJ2XN-FW8RK-P4HMP-DKDBV-GCVGB
---Processing--------------------------
---------------------------------------
ERROR CODE: 0xC004F069
ERROR DESCRIPTION: The Software Licensing Service reported that the product SKU is not found.

3. This issue after I run ospp.vbs with /dstatus
C:\Windows\system32>cscript //nologo "C:\Program Files\Microsoft Office\Office16\ospp.vbs" /dstatus
---Processing--------------------------
---------------------------------------
PRODUCT ID: 00511-70000-00000-AA159
SKU ID: 24996154-f927-413f-b2d5-c81882464ee3
LICENSE NAME: Office 24, Office24ProPlus2024R_Grace edition
LICENSE DESCRIPTION: Office 24, RETAIL(Grace) channel
BETA EXPIRATION: 1/01/1601
LICENSE STATUS:  ---OOB_GRACE---
ERROR CODE: 0x4004F00C
ERROR DESCRIPTION: The Software Licensing Service reported that the application is running within the valid grace period.
REMAINING GRACE: 4 days  (7195 minute(s) before expiring)
Last 5 characters of installed product key: R9GQV
---------------------------------------
---------------------------------------
---Exiting-----------------------------

**Comment by ichadhr** [comment]
You use the retail version, please use this tools to deploy office [https://github.com/YerongAI/Office-Tool/tree/main](https://github.com/YerongAI/Office-Tool/tree/main)
Deploy config: `Update channel: Office 2024 Perpetual Enterprise`

[Office Products Information](https://github.com/YerongAI/Office-Tool/blob/main/doc/Tech%20Articles/Products.md)

**Comment by kimchheng-dev** [comment]
@ichadhr thanks it works with deployment method.
https://learn.microsoft.com/en-us/office/ltsc/2024/deploy

**Comment by kimchheng-dev** [comment]
@ichadhr thanks it works with deployment method.
https://learn.microsoft.com/en-us/office/ltsc/2024/deploy
