### ISSUE TITLE
"latest" update not working

### ISSUE THREAD

**Issue by lepoarro** [Py-KMS-Organization/py-kms#14]
I was running my py-kms (docker) on UNRAID server and now after latest update it stopped working.
This is the error what was shown:
`Traceback (most recent call last):
File "/usr/bin/entrypoint.py", line 28, in <module>
enableSQLITE = os.environ.get('SQLITE').lower() == 'true'
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
File "/usr/bin/entrypoint.py", line 28, in <module>
enableSQLITE = os.environ.get('SQLITE').lower() == 'true'
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
File "/usr/bin/entrypoint.py", line 28, in <module>
enableSQLITE = os.environ.get('SQLITE').lower() == 'true'
AttributeError: 'NoneType' object has no attribute 'lower'`
Need to get it working again!!! Please!

**Comment by lepoarro** [comment]
Got it working. Changed the docker tag from "latest" to "python3" and got it running again.

**Comment by simonmicro** [comment]
Just fixed it. Thanks for the notice!
