### ISSUE TITLE
Set own UID/GID in Docker

### ISSUE THREAD

**Issue by simonmicro** [Py-KMS-Organization/py-kms#15]
I have TZ ok (through env var)+ log for client on stdout. 
I try to change now uid/gid of user as I need to have specific id/gid on mounted volume and drop root privileges after having set TZ and UID/GID.. without any luck til now. I might have to split entrypoint in 2. My fork might be already to different from yours.

_Originally posted by @edgd1er in https://github.com/Py-KMS-Organization/py-kms/issues/10#issuecomment-943844930_

**Comment by simonmicro** [comment]
Did you take a look into [here](https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15) ? As far as I can tell you / we could just extend the `docker run` command or change the `docker-compose` respectively. But yes, we should drop any py-kms privileges and run as user `1000` inside the container.

**Comment by edgd1er** [comment]
Starting with endpoint with root privileges allows, then start.py is run with dropped privileges.
the two step process allows:
- defined timezone according to TZ env var
- define user id et group ip as defined in UID/GUID env var
- set file ownership as required by new UID/GID
- run bash as root to perform some tests/validation.

Another solution would be to run the commands (through os.system + sudo + chmod / chroup / chown ).
I'm not sure what is best.

in my setup, i need to check/set database file rights and only root has enough privileges to do it whatever are the database file rights.

At the moment, the container is run with root privileges.
