### ISSUE TITLE
Dockerfiles are cloning from original repo

### ISSUE THREAD

**Issue by TheSpad** [Py-KMS-Organization/py-kms#2]
Dockerfiles are cloning from original repo and not this forked one.

https://github.com/Py-KMS-Organization/py-kms/blob/master/docker/docker-py3-kms-minimal/Dockerfile#L28

https://github.com/Py-KMS-Organization/py-kms/blob/master/docker/docker-py3-kms/Dockerfile#L28

**Comment by simonmicro** [comment]
Shit. I've missed that! I'll be fixing that ASAP. Sorry.

**Comment by simonmicro** [comment]
Thanks!
