### ISSUE TITLE
Issue with Office LTSC Standard 2021

### ISSUE THREAD

**Issue by MartinKuhl** [Py-KMS-Organization/py-kms#25]
I am not able to activate 

DOCKER Log:
Sat, 23 Oct 2021 18:42:14 INFO     RPC bind request received.
Sat, 23 Oct 2021 18:42:14 INFO     RPC bind acknowledged.
Sat, 23 Oct 2021 18:42:14 INFO     Received activation request.
Sat, 23 Oct 2021 18:42:14 INFO     Received V6 request on Sat Oct 23 18:42:14 2021.
Sat, 23 Oct 2021 18:42:14 WARNING  Too many clients ! Fixed with 10
Sat, 23 Oct 2021 18:42:15 INFO     Machine Name: XXX
Sat, 23 Oct 2021 18:42:15 INFO     Client Machine ID: XYXYXYXY
Sat, 23 Oct 2021 18:42:15 INFO     Application ID: Office 15 (2013) / 16 (2016) / 17 (2019)
Sat, 23 Oct 2021 18:42:15 INFO     SKU ID: Office LTSC Standard 2021
Sat, 23 Oct 2021 18:42:15 INFO     License Status: Grace Period
Sat, 23 Oct 2021 18:42:15 INFO     Request Time: 2021-10-23 18:42:12 UTC (UTC+0000)
Sat, 23 Oct 2021 18:42:15 INFO     Connection closed: 172.17.0.1:59084

In the Windows Terminal I get the following error details:
ERROR CODE: 0xC004F074
ERROR DESCRIPTION: The Software Licensing Service reported that the product could not be activated. No Key Management Service (KMS) could be contacted. Please see the Application Event Log for additional information.

Any ideas?

**Comment by larrywhitlock** [comment]
I tried to tell him yesterday that the code didn't work on the branch Office 2021 build and he pushed it to master.

If you have access to the KmsDataBase.xml file.
Change Line 551:
`       <CsvlkItem DisplayName="Office 2021" VlmcsdIndex="6" GroupId="206" MinKeyId="571000000" MaxKeyId="590999999" IniFileName="Office2021" EPid="05426-00206-586-025264-03-1033-9200.0000-2602021" Id="47f3b983-7c53-4d45-abc6-bcd91e2dd90a" InvalidWinBuild="[0,1]">`

**Comment by simonmicro** [comment]
@larrywhitlock Oh sorry, I did not understood that you also tried the `preview/office21` branch! So to clarify: The current master can NOT activate Office 21 even with the extended database? And all we need is to remove the `ReleaseDate` attribute and instead add the `InvalidWinBuild` attribute? Because to me those lines look very similar and should NOT cause this - hmm, maybe the code expect the latter property (I'll add it just in case)?...

```
<CsvlkItem DisplayName="Office 2021" VlmcsdIndex="6" GroupId="206" MinKeyId="571000000" MaxKeyId="590999999" IniFileName="Office2021" EPid="05426-00206-586-025264-03-1033-9200.0000-2602021" Id="47f3b983-7c53-4d45-abc6-bcd91e2dd90a" InvalidWinBuild="[0,1]">
```
```
<CsvlkItem DisplayName="Office 2021" VlmcsdIndex="6" GroupId="206" MinKeyId="571000000" MaxKeyId="590999999" IniFileName="Office2021" ReleaseDate="2021-09-16T00:00:00Z" EPid="05426-00206-586-025264-03-1033-9200.0000-2602021" Id="47f3b983-7c53-4d45-abc6-bcd91e2dd90a">
```

**Comment by larrywhitlock** [comment]
Correct, taking the release date out by itself didn't work, so I added the ending code and it started working.

**Comment by larrywhitlock** [comment]
I'll be able to check it in 15 minutes.

**Comment by larrywhitlock** [comment]
BINGO!
We have a Winner.... Office 20221 Pro Plus, Visio Pro Plus, Project Pro Plus... Activated!
