### ISSUE TITLE
INFO ONLY: PHP Viewer for sqlite3 py-kms db-file

### ISSUE THREAD

**Issue by arturolegovich** [Py-KMS-Organization/py-kms#32]
Hi.
Wrote for myself a PHP application to view sqlite3 py-kms database.
Maybe someone will be useful someday like me.

Soon I will start writing an application for viewing a database in python, instead of sqlite-web.

https://github.com/arturolegovich/py-kms_phpviewer-sqlite3

**Comment by Matthew-Beckett** [comment]
Please add as markdown to the official [documentation](https://github.com/Py-KMS-Organization/py-kms/tree/master/docs), we cannot keep issues that contain information perpetually open as they are required for bug tracking.
