### ISSUE TITLE
Add LTSC 2021 GVLK

### ISSUE THREAD

**Issue by CreeperKong** [Py-KMS-Organization/py-kms#34]
PG7H6-7RNT3-R4MGR-HMJK2-J462D

**Comment by Matthew-Beckett** [comment]
Hi @CreeperKong,

Would you mind adding this via PR to the official documentation?

https://github.com/Py-KMS-Organization/py-kms/blob/master/docs/Keys.md

**Comment by simonmicro** [comment]
Sorry, but we will only include such keys if we can get them from a legal source - the key you are writing here only shows up in shady places. Feel free to reopen this issue or even to create an PR if you can prove this key is from a legitimate source.

Sorry.
