### ISSUE TITLE
Add Windows 11 licenses.

### ISSUE THREAD

**Issue by AraHaan** [Py-KMS-Organization/py-kms#35]
https://docs.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys#windows-11-and-windows-10-semi-annual-channel-versions

**Comment by Matthew-Beckett** [comment]
Hi @AraHaan 

Would you mind adding this via PR to the official documentation?

https://github.com/Py-KMS-Organization/py-kms/blob/master/docs/Keys.md

**Comment by simonmicro** [comment]
This was done long ago via f93ea7f7a5f029cccd0b0aeb63a38b4bbdb2d41d - no need for further changes.
