### ISSUE TITLE
Server 2022 KMSItem

### ISSUE THREAD

**Issue by echodreamz** [Py-KMS-Organization/py-kms#53]
I see Server 2022 is shown as supported, but I do not see any XML entries for it in the KmsDataBase.xml file.

**Comment by simonmicro** [comment]
Does it work? Then we do not need to add them... If not - our bad.

**Comment by echodreamz** [comment]
They do work, though, there are no entries specific for Server 2022, so not sure how it is working. So I do not see a way to add our KMS specific keys like older versions of Windows.

**Comment by Hacksawfred3232** [comment]
> They do work, though, there are no entries specific for Server 2022, so not sure how it is working. So I do not see a way to add our KMS specific keys like older versions of Windows.

Considering I was testing Windows Server 2022 earlier for a later deployment and it looks mostly like Windows 10 but with an 11 skin slapped on, I think they still use the old protocol/XML Entry. Micro$oft being lazy as always.

**Comment by pvgoran** [comment]
The current update of Windows Server 2022 (OS build 20348.1366) refuses to activate when connecting to py-kms (revision 1435c86fe4f11aa7fd42d77fa61715ca3015eeab). After I applied the changes from #57, it activated.

@simonmicro Please consider merging #57.

**Comment by pvgoran** [comment]
Correction: I used a different py-kms revision, a3b0c85b5b90f63b33dfa5ae6085fcd52c6da2ff. (But it doesn't seem to change the overall picture.)
