### ISSUE TITLE
Error: 0x8007232B DNS name does not exist

### ISSUE THREAD

**Issue by tpimh** [Py-KMS-Organization/py-kms#60]
I'm running `pykmsorg/py-kms:python3` in my local IPv4 only network. Trying to activate Windows 10 Pro with a GVLK Key.

```
> nslookup -type=srv _vlmcs._tcp
Server:  *my DNS server hostname*
Address:  *my DNS server IP*

_vlmcs._tcp     SRV service location:
          priority       = 20
          weight         = 0
          port           = 1688
          svr hostname   = *my container hostname*
kms.lahtihosting.fi     internet address = *my container IP*

> Test-NetConnection *my container hostname* -Port 1688
ComputerName     : *my container hostname*
RemoteAddress    : *my container IP*
RemotePort       : 1688
InterfaceAlias   : *my adapter name*
SourceAddress    : *my computer IP*
TcpTestSucceeded : True
```

However, `slmgr /ato` produces this error: `Error: 0x8007232B DNS name does not exist`.

Settings -> Activation has this text in red:

> We can’t activate Windows on this device as we can’t connect to your organization’s activation server. Make sure that you’re connected to your organization’s network and try again. If you continue having problems with activation, contact your organization’s support person. Error code: 0x8007007B

Is it a problem with py-kms or my network? What am I doing wrong?

**Comment by Matthew-Beckett** [comment]
Hi @tpimh,

This is something which has come up in the past, please can you provide outputs with generalised host names as opposed to redacted as it makes it impossible to tell if your DNS solution is working as it should be.

Also, it may be helpful to refer to this thread where this issue has come up in the past, it may be full of useful information which may help you on your quest.

https://github.com/Py-KMS-Organization/py-kms/issues/45

Thanks,
Matt

**Comment by tpimh** [comment]
Hi Matt!

Thank you very much for a prompt reply! Here is the unedited output (I guess I don't have anything to hide here):

```
PS C:\Users\admin> nslookup -type=srv _vlmcs._tcp
Server:  pi.hole
Address:  10.0.0.222

_vlmcs._tcp     SRV service location:
          priority       = 20
          weight         = 0
          port           = 1688
          svr hostname   = kms.lahtihosting.fi
kms.lahtihosting.fi     internet address = 10.0.0.227
PS C:\Users\admin> Test-NetConnection kms.lahtihosting.fi -Port 1688


ComputerName     : kms.lahtihosting.fi
RemoteAddress    : 10.0.0.227
RemotePort       : 1688
InterfaceAlias   : Ethernet 2
SourceAddress    : 10.0.0.20
TcpTestSucceeded : True
```

The copy of Windows that I'm trying to activate is not a new installation, it was installed from an official Microsoft ISO, none of the DLLs were replaced to third party versions, it was previously activated with a different key (not GVLK), but I have reset the activation with `slmgr /upk`. Also, when manually specifying the server with `slmgr /skms kms.lahtihosting.fi:1688`, the activation is successful. I think you are right about the reason for this behavior being connected with DNS search domain suffix and AD, I will look more into this.

**Comment by simonmicro** [comment]
Hey,

good that @Matthew-Beckett already explained this (:heart:). I think Microsoft should update their docs to state in big, fat, red letters that using the SRV entry in DNS does only work in AD environments. I think this should solve your problem.

_One final note_ Please refrain from using publicly accessible hostnames (like `lahtihosting.fi`) as Microsoft will scan those and send you a nice DMCA for providing this service.

Greetings...

**Comment by tpimh** [comment]
Hi Simon! I have no plans of providing such service, the subdomain only exists in a private network. All my copies of Windows are legit, and I'm using py-kms strictly for research purposes, so I really do think I'm not breaking any rules or laws. However, I have edited my messages, but the information is still there in the edit history.
