### ISSUE TITLE
Feature request : Support Server 2003 and XP

### ISSUE THREAD

**Issue by Zulgrib** [Py-KMS-Organization/py-kms#70]
For the sake of completeness, is it possible to support XP and 2003 (R2) ?

These system are loved for running old software, and official activation methods are harder to use over time for these old operating system.
Unofficial methods documentation gets lost (links are now 404). The cleanest way would be to use slmgr.vbs /skms

Of course, I do not recommend running these system on something else than an air gaped network without internet.

**Comment by rijenkii** [comment]
I'm pretty sure that KMS was introduced with Vista, so XP and 2003 can't activate against a KMS.

**Comment by luky92** [comment]
You can't activate XP against KMS so by extension you can't activate server
2003 either

W dniu śr., 18.05.2022 o 10:05 rijenkii ***@***.***>
napisał(a):

**Comment by simonmicro** [comment]
Thank you very much @rijenkii and @luky92 for your explanation! Sadly, these old versions can't be activated with this project. I would recommend you to look for ways of modifying the OS directly (no links here!).
