### ISSUE TITLE
Use dual-stack by default

### ISSUE THREAD

**Issue by DerEnderKeks** [Py-KMS-Organization/py-kms#71]
I just wasted way too much time trying to figure out why the kms server was unreachable on my IPv6 K8s cluster just to find out that py-kms only listens on legacy IPv4 by default. It's 2022, this really shouldn't be happening anymore.

**Comment by simonmicro** [comment]
Indeed - I remember in the original repo we had some problems using this any my change was reverted. @Matthew-Beckett what do you think? Should we try again?

**Comment by Matthew-Beckett** [comment]
@DerEnderKeks can you test #79?

**Comment by simonmicro** [comment]
So, I assume this is resolved now.
