### ISSUE TITLE
Error while activating 0x80070000d

### ISSUE THREAD

**Issue by daniandco1** [Py-KMS-Organization/py-kms#74]
kms actication the data is invalid 0x80070000d
im getting this error while trying to run my server on my local network (docker) and trying to activate on the same network.

i do know that it happens because **i run server and client on the same computer** and running the server on virtualbox fixed my issue

 however,
 * i think docker can do bridge networking by himself * (without virtualbox).

so the question is: how to run server and client on the same computer using docker?

**Comment by simonmicro** [comment]
You don't. Because Docker will create a new Network Interface, which is marked as `local` in Windows. This way any communication over that interface will still be treated as "from the same machine". You could try to use Swarm and this way bridge it over?

**Comment by Matthew-Beckett** [comment]
> You don't. Because Docker will create a new Network Interface, which is marked as `local` in Windows. This way any communication over that interface will still be treated as "from the same machine". You could try to use Swarm and this way bridge it over? 

@simonmicro is there specific limitations in place to prevent the KMS protocol being usable over a local/loop back interface? 

Is this an attempt to prevent you running a local KMS impersonator as this project does?

**Comment by simonmicro** [comment]
> @simonmicro is there specific limitations in place to prevent the KMS protocol being usable over a local/loop back interface?

Something, something Windows?

> Is this an attempt to prevent you running a local KMS impersonator as this project does?

Bingo. I see NO reason why Microsoft should implement this limitation otherwise!
