### ISSUE TITLE
Connect GUI to remote server?

### ISSUE THREAD

**Issue by ajh123** [Py-KMS-Organization/py-kms#75]
This would allow someone to run pykms in Docker and then use a client program to have access to the GUI. Curently we have no way to view to GUI of a pykms server in Docker, so having a way to 'connect' to it would allow us to view the GUI. This would also allow for management of a pykms server remotely (or across the internet if the port has been forwarded correctly.

**Comment by simonmicro** [comment]
Implemented with #82
