### ISSUE TITLE
Office Professional 2021 Volume License

### ISSUE THREAD

**Issue by Knightr1702** [Py-KMS-Organization/py-kms#8]
I am wondering if py-kms is going to be updated to include Office Professional 2021 Volume License?  Thanks.

**Comment by BurningC4** [comment]
https://forums.mydigitallife.net/threads/emulated-kms-servers-on-non-windows-platforms.50234/page-97#post-1690179

**Comment by simonmicro** [comment]
Thanks, could someone test and verify https://github.com/Py-KMS-Organization/py-kms/tree/preview/office21 ? I have extended the database and listed the new keys.

**Comment by Knightr1702** [comment]
I Will.  Thanks
