### ISSUE TITLE
Windows kms error

### ISSUE THREAD

**Issue by maximuslotro** [Py-KMS-Organization/py-kms#85]
When trying to run `slmgr.vbs /ato` after adding a valid server `/skms` and key `/ipk` i get the error 

`Error: 0xC004F074 The Software Licensing Service reported that the computer could not be activated. No Key Management Service (KMS) could be contacted. Please see the Application Event Log for additional information.` 

Does this mean i haven't opened the correct port, or that this doesn't support windows 10/11 22H2/22H1 or both?

**Comment by luky92** [comment]
Seems like a network/configuration issue

czw., 9 lut 2023, 04:16 użytkownik maximuslotro ***@***.***>
napisał:
