### ISSUE TITLE
Docker Container says unhealthy but logs show nothing

### ISSUE THREAD

**Issue by dudefoxlive** [Py-KMS-Organization/py-kms#89]
Recently I have noticed that in portainer I see that my Py-KMS is showing as unhealthy. I look in the logs and see that its blank. Any reason as to why this is the case?
![image](https://user-images.githubusercontent.com/50186495/236313024-a8a92ce9-f0c6-4d9b-8550-ac0aa82cc612.png)

**Comment by didotb** [comment]
restart the container, and while it's starting check the console outputs those could have something as well

**Comment by simonmicro** [comment]
@dudefoxlive Would you be able to also share your used environment variables? Maybe you've enabled a feature with a "feature"...

**Comment by simonmicro** [comment]
Also setting `LOGLEVEL` to e.g. `DEBUG` could help.

**Comment by simonmicro** [comment]
Nah, got it! With the new dual-stack default of `::` the healthcheck for native Docker was broken...
