### ISSUE TITLE
Not activating

### ISSUE THREAD

**Issue by sbach89** [Py-KMS-Organization/py-kms#9]
Receiving the following when attempting to activate Windows server 2022 after pulling latest python3 image. 

Wed, 13 Oct 2021 10:25:29 INFO     Machine Name: xxx
Wed, 13 Oct 2021 10:25:29 INFO     Client Machine ID: a1597c43-9243-4160-83f4-a1b4ff788ee7
Wed, 13 Oct 2021 10:25:29 INFO     Application ID: Windows
Wed, 13 Oct 2021 10:25:29 INFO     SKU ID: ef6cfc9f-8c5d-44ac-9aad-de6a2ea0ae03
Wed, 13 Oct 2021 10:25:29 INFO     License Status: Notifications Mode
Wed, 13 Oct 2021 10:25:29 INFO     Request Time: 2021-10-13 14:25:28  (UTC)
Wed, 13 Oct 2021 10:25:29 ERROR    Sqlite Error: no such table: clients. Exiting...
Wed, 13 Oct 2021 10:25:29 INFO     Connection closed: 192.168.1.13:49709

**Comment by ritmo2k1024** [comment]
It doesn't look like the `KmsDataBase.xml` file has a definition for Windows Server 2022 yet.

**Comment by sbach89** [comment]
Works now, and server 2022 activates as well as Win 11 and Office 2021. Thank you
