### ISSUE TITLE
Windows 10 LTSC Enterprise keys 2021 missing keys

### ISSUE THREAD

**Issue by tylerhoot** [Py-KMS-Organization/py-kms#94]
Windows  Windows 10 LTSC Enterprise keys 2021
KMS Key: M7XTQ-FN8P6-TTKYV-9D4CC-J462D
https://web.archive.org/web/20230401175111/https://www.reddit.com/r/Windows10LTSC/comments/qw1qrs/ltsc_2021_vs_iot_ltsc_2021_tips_on_installations/

**Comment by simonmicro** [comment]
Related to #96 ?

**Comment by tylerhoot** [comment]
It's is a embedded version of windows 10 stripped down

**Comment by didotb** [comment]
can you provide the SKU ID?
that's what we currently need

once you have a device activated, you can perform `slmgr.vbs /dlv`, the SKU ID is the `Activation ID: ` right below `Description: `
